---
  deployment:
    tasks:
      - export DEPLOYPATH=/home2/txlxmqol/public_html/CssGameTheory/
      - /bin/cp -r JavaScript $DEPLOYPATH
      - /bin/cp -r HTML $DEPLOYPATH
      - /bin/cp -r css $DEPLOYPATH
      - /bin/cp -r Img $DEPLOYPATH
      - /bin/cp .env $DEPLOYPATH
      - /bin/cp .gitignore $DEPLOYPATH
      - /bin/cp .cpanel.yml $DEPLOYPATH
      - /bin/cp env.php $DEPLOYPATH
      - /bin/cp package.json
      - /bin/cp package-lock.json
      - /bin/cp index.js